bootstrap:
	cdk bootstrap --profile nftquant
deploy:
	cdk deploy -c stage=dev --profile nftquant --all
deploy-appsync:
	cdk deploy dev-NFTM-GraphQL-appsync -c stage=dev --profile nftquant 
deploy-market:
	cdk deploy dev-NFTM-Market -c stage=dev --profile nftquant 
deploy-core:
	cdk deploy dev-NFTM-Core -c stage=dev --profile nftquant 
deploy-user:
	cdk deploy dev-NFTM -c stage=dev --profile nftquant 
