// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: expose/orderbook.proto

// import "google/protobuf/empty.proto";

package orderbook

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SideOrder int32

const (
	SideOrder_BUY  SideOrder = 0
	SideOrder_SELL SideOrder = 1
)

// Enum value maps for SideOrder.
var (
	SideOrder_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	SideOrder_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x SideOrder) Enum() *SideOrder {
	p := new(SideOrder)
	*p = x
	return p
}

func (x SideOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SideOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_expose_orderbook_proto_enumTypes[0].Descriptor()
}

func (SideOrder) Type() protoreflect.EnumType {
	return &file_expose_orderbook_proto_enumTypes[0]
}

func (x SideOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SideOrder.Descriptor instead.
func (SideOrder) EnumDescriptor() ([]byte, []int) {
	return file_expose_orderbook_proto_rawDescGZIP(), []int{0}
}

type Prices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64         `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Asks      []*PriceLevel `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids      []*PriceLevel `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
	Pair      string        `protobuf:"bytes,4,opt,name=pair,proto3" json:"pair,omitempty"`
}

func (x *Prices) Reset() {
	*x = Prices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prices) ProtoMessage() {}

func (x *Prices) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prices.ProtoReflect.Descriptor instead.
func (*Prices) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *Prices) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Prices) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *Prices) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *Prices) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

type PriceLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price    string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity string `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *PriceLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceLevel) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Side      SideOrder `protobuf:"varint,1,opt,name=side,proto3,enum=orderbook.SideOrder" json:"side,omitempty"`
	Id        string    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp int64     `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Quantity  int64     `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price     int64     `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetSide() SideOrder {
	if x != nil {
		return x.Side
	}
	return SideOrder_BUY
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Order) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CancelOrderArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair    string `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	OrderId string `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
}

func (x *CancelOrderArgs) Reset() {
	*x = CancelOrderArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelOrderArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderArgs) ProtoMessage() {}

func (x *CancelOrderArgs) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderArgs.ProtoReflect.Descriptor instead.
func (*CancelOrderArgs) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderArgs) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *CancelOrderArgs) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrderResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CancelOrderResult) Reset() {
	*x = CancelOrderResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelOrderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResult) ProtoMessage() {}

func (x *CancelOrderResult) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResult.ProtoReflect.Descriptor instead.
func (*CancelOrderResult) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOrderResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubscribeArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair string `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
}

func (x *SubscribeArgs) Reset() {
	*x = SubscribeArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeArgs) ProtoMessage() {}

func (x *SubscribeArgs) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeArgs.ProtoReflect.Descriptor instead.
func (*SubscribeArgs) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeArgs) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

// args
// Limit: side ob.Side, orderID string, quantity decimal.Decimal, price decimal.Decimal
type NewLimitOrderArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair     string    `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Side     SideOrder `protobuf:"varint,3,opt,name=side,proto3,enum=orderbook.SideOrder" json:"side,omitempty"`
	OrderId  string    `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Quantity int64     `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price    int64     `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *NewLimitOrderArgs) Reset() {
	*x = NewLimitOrderArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewLimitOrderArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLimitOrderArgs) ProtoMessage() {}

func (x *NewLimitOrderArgs) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLimitOrderArgs.ProtoReflect.Descriptor instead.
func (*NewLimitOrderArgs) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_proto_rawDescGZIP(), []int{6}
}

func (x *NewLimitOrderArgs) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *NewLimitOrderArgs) GetSide() SideOrder {
	if x != nil {
		return x.Side
	}
	return SideOrder_BUY
}

func (x *NewLimitOrderArgs) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *NewLimitOrderArgs) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *NewLimitOrderArgs) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type NewLimitOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order                    []*Order `protobuf:"bytes,1,rep,name=order,proto3" json:"order,omitempty"`
	Partial                  *Order   `protobuf:"bytes,2,opt,name=partial,proto3" json:"partial,omitempty"`
	PartialQuantityProcessed int64    `protobuf:"varint,3,opt,name=partialQuantityProcessed,proto3" json:"partialQuantityProcessed,omitempty"`
	TransactionTime          string   `protobuf:"bytes,4,opt,name=transactionTime,proto3" json:"transactionTime,omitempty"`
}

func (x *NewLimitOrderResponse) Reset() {
	*x = NewLimitOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewLimitOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLimitOrderResponse) ProtoMessage() {}

func (x *NewLimitOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLimitOrderResponse.ProtoReflect.Descriptor instead.
func (*NewLimitOrderResponse) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_proto_rawDescGZIP(), []int{7}
}

func (x *NewLimitOrderResponse) GetOrder() []*Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *NewLimitOrderResponse) GetPartial() *Order {
	if x != nil {
		return x.Partial
	}
	return nil
}

func (x *NewLimitOrderResponse) GetPartialQuantityProcessed() int64 {
	if x != nil {
		return x.PartialQuantityProcessed
	}
	return 0
}

func (x *NewLimitOrderResponse) GetTransactionTime() string {
	if x != nil {
		return x.TransactionTime
	}
	return ""
}

type NewMarketOrderArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair     string    `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Side     SideOrder `protobuf:"varint,3,opt,name=side,proto3,enum=orderbook.SideOrder" json:"side,omitempty"`
	Quantity int64     `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *NewMarketOrderArgs) Reset() {
	*x = NewMarketOrderArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewMarketOrderArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMarketOrderArgs) ProtoMessage() {}

func (x *NewMarketOrderArgs) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMarketOrderArgs.ProtoReflect.Descriptor instead.
func (*NewMarketOrderArgs) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_proto_rawDescGZIP(), []int{8}
}

func (x *NewMarketOrderArgs) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *NewMarketOrderArgs) GetSide() SideOrder {
	if x != nil {
		return x.Side
	}
	return SideOrder_BUY
}

func (x *NewMarketOrderArgs) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type NewMarketOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order                    []*Order `protobuf:"bytes,1,rep,name=order,proto3" json:"order,omitempty"`
	Partial                  *Order   `protobuf:"bytes,2,opt,name=partial,proto3" json:"partial,omitempty"`
	PartialQuantityProcessed int64    `protobuf:"varint,3,opt,name=partialQuantityProcessed,proto3" json:"partialQuantityProcessed,omitempty"`
	QuantityLeft             int64    `protobuf:"varint,4,opt,name=quantityLeft,proto3" json:"quantityLeft,omitempty"`
	TransactionTime          string   `protobuf:"bytes,5,opt,name=transactionTime,proto3" json:"transactionTime,omitempty"`
}

func (x *NewMarketOrderResponse) Reset() {
	*x = NewMarketOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewMarketOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMarketOrderResponse) ProtoMessage() {}

func (x *NewMarketOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMarketOrderResponse.ProtoReflect.Descriptor instead.
func (*NewMarketOrderResponse) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_proto_rawDescGZIP(), []int{9}
}

func (x *NewMarketOrderResponse) GetOrder() []*Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *NewMarketOrderResponse) GetPartial() *Order {
	if x != nil {
		return x.Partial
	}
	return nil
}

func (x *NewMarketOrderResponse) GetPartialQuantityProcessed() int64 {
	if x != nil {
		return x.PartialQuantityProcessed
	}
	return 0
}

func (x *NewMarketOrderResponse) GetQuantityLeft() int64 {
	if x != nil {
		return x.QuantityLeft
	}
	return 0
}

func (x *NewMarketOrderResponse) GetTransactionTime() string {
	if x != nil {
		return x.TransactionTime
	}
	return ""
}

var File_expose_orderbook_proto protoreflect.FileDescriptor

var file_expose_orderbook_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f,
	0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62,
	0x6f, 0x6f, 0x6b, 0x22, 0x90, 0x01, 0x0a, 0x06, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x29, 0x0a, 0x04,
	0x61, 0x73, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x52, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f,
	0x6b, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x04, 0x62, 0x69,
	0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x22, 0x3e, 0x0a, 0x0a, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x91, 0x01, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x28, 0x0a, 0x04, 0x73, 0x69, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x3f, 0x0a, 0x0f, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x11, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x23, 0x0a, 0x0d, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x22,
	0x9d, 0x01, 0x0a, 0x11, 0x4e, 0x65, 0x77, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x12, 0x28, 0x0a, 0x04, 0x73, 0x69, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62,
	0x6f, 0x6f, 0x6b, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x04, 0x73,
	0x69, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22,
	0xd1, 0x01, 0x0a, 0x15, 0x4e, 0x65, 0x77, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x07, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x3a, 0x0a,
	0x18, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x18, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x6e, 0x0a, 0x12, 0x4e, 0x65, 0x77, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x69,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x12, 0x28, 0x0a,
	0x04, 0x73, 0x69, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x22, 0xf6, 0x01, 0x0a, 0x16, 0x4e, 0x65, 0x77, 0x4d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26,
	0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62,
	0x6f, 0x6f, 0x6b, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x07, 0x70, 0x61, 0x72, 0x74, 0x69,
	0x61, 0x6c, 0x12, 0x3a, 0x0a, 0x18, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x51, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x18, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x51, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x65, 0x66, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x65,
	0x66, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x2a, 0x1e, 0x0a, 0x09,
	0x53, 0x69, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x55, 0x59,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4c, 0x4c, 0x10, 0x01, 0x32, 0xbf, 0x02, 0x0a,
	0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x3e, 0x0a, 0x0b, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4c, 0x32, 0x12, 0x18, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41,
	0x72, 0x67, 0x73, 0x1a, 0x11, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01, 0x12, 0x51, 0x0a, 0x0d, 0x4e, 0x65,
	0x77, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x4e, 0x65, 0x77, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x20, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x4e, 0x65, 0x77, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a,
	0x0e, 0x4e, 0x65, 0x77, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x1d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x4e, 0x65, 0x77, 0x4d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x21,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x4e, 0x65, 0x77, 0x4d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0b, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x1a, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x1c,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x50,
	0x0a, 0x1a, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x73, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x42, 0x0e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x20,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_expose_orderbook_proto_rawDescOnce sync.Once
	file_expose_orderbook_proto_rawDescData = file_expose_orderbook_proto_rawDesc
)

func file_expose_orderbook_proto_rawDescGZIP() []byte {
	file_expose_orderbook_proto_rawDescOnce.Do(func() {
		file_expose_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(file_expose_orderbook_proto_rawDescData)
	})
	return file_expose_orderbook_proto_rawDescData
}

var file_expose_orderbook_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_expose_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_expose_orderbook_proto_goTypes = []interface{}{
	(SideOrder)(0),                 // 0: orderbook.SideOrder
	(*Prices)(nil),                 // 1: orderbook.Prices
	(*PriceLevel)(nil),             // 2: orderbook.PriceLevel
	(*Order)(nil),                  // 3: orderbook.Order
	(*CancelOrderArgs)(nil),        // 4: orderbook.CancelOrderArgs
	(*CancelOrderResult)(nil),      // 5: orderbook.CancelOrderResult
	(*SubscribeArgs)(nil),          // 6: orderbook.SubscribeArgs
	(*NewLimitOrderArgs)(nil),      // 7: orderbook.NewLimitOrderArgs
	(*NewLimitOrderResponse)(nil),  // 8: orderbook.NewLimitOrderResponse
	(*NewMarketOrderArgs)(nil),     // 9: orderbook.NewMarketOrderArgs
	(*NewMarketOrderResponse)(nil), // 10: orderbook.NewMarketOrderResponse
}
var file_expose_orderbook_proto_depIdxs = []int32{
	2,  // 0: orderbook.Prices.asks:type_name -> orderbook.PriceLevel
	2,  // 1: orderbook.Prices.bids:type_name -> orderbook.PriceLevel
	0,  // 2: orderbook.Order.side:type_name -> orderbook.SideOrder
	0,  // 3: orderbook.NewLimitOrderArgs.side:type_name -> orderbook.SideOrder
	3,  // 4: orderbook.NewLimitOrderResponse.order:type_name -> orderbook.Order
	3,  // 5: orderbook.NewLimitOrderResponse.partial:type_name -> orderbook.Order
	0,  // 6: orderbook.NewMarketOrderArgs.side:type_name -> orderbook.SideOrder
	3,  // 7: orderbook.NewMarketOrderResponse.order:type_name -> orderbook.Order
	3,  // 8: orderbook.NewMarketOrderResponse.partial:type_name -> orderbook.Order
	6,  // 9: orderbook.Orderbook.SubscribeL2:input_type -> orderbook.SubscribeArgs
	7,  // 10: orderbook.Orderbook.NewLimitOrder:input_type -> orderbook.NewLimitOrderArgs
	9,  // 11: orderbook.Orderbook.NewMarketOrder:input_type -> orderbook.NewMarketOrderArgs
	4,  // 12: orderbook.Orderbook.CancelOrder:input_type -> orderbook.CancelOrderArgs
	1,  // 13: orderbook.Orderbook.SubscribeL2:output_type -> orderbook.Prices
	8,  // 14: orderbook.Orderbook.NewLimitOrder:output_type -> orderbook.NewLimitOrderResponse
	10, // 15: orderbook.Orderbook.NewMarketOrder:output_type -> orderbook.NewMarketOrderResponse
	5,  // 16: orderbook.Orderbook.CancelOrder:output_type -> orderbook.CancelOrderResult
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_expose_orderbook_proto_init() }
func file_expose_orderbook_proto_init() {
	if File_expose_orderbook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_expose_orderbook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelOrderArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelOrderResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewLimitOrderArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewLimitOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewMarketOrderArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewMarketOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_expose_orderbook_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expose_orderbook_proto_goTypes,
		DependencyIndexes: file_expose_orderbook_proto_depIdxs,
		EnumInfos:         file_expose_orderbook_proto_enumTypes,
		MessageInfos:      file_expose_orderbook_proto_msgTypes,
	}.Build()
	File_expose_orderbook_proto = out.File
	file_expose_orderbook_proto_rawDesc = nil
	file_expose_orderbook_proto_goTypes = nil
	file_expose_orderbook_proto_depIdxs = nil
}
