// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: expose/orderbook/orderbook.proto

package orderbook

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypeOrder int32

const (
	TypeOrder_LIMIT  TypeOrder = 0
	TypeOrder_MARKET TypeOrder = 1
)

// Enum value maps for TypeOrder.
var (
	TypeOrder_name = map[int32]string{
		0: "LIMIT",
		1: "MARKET",
	}
	TypeOrder_value = map[string]int32{
		"LIMIT":  0,
		"MARKET": 1,
	}
)

func (x TypeOrder) Enum() *TypeOrder {
	p := new(TypeOrder)
	*p = x
	return p
}

func (x TypeOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_expose_orderbook_orderbook_proto_enumTypes[0].Descriptor()
}

func (TypeOrder) Type() protoreflect.EnumType {
	return &file_expose_orderbook_orderbook_proto_enumTypes[0]
}

func (x TypeOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeOrder.Descriptor instead.
func (TypeOrder) EnumDescriptor() ([]byte, []int) {
	return file_expose_orderbook_orderbook_proto_rawDescGZIP(), []int{0}
}

type SideOrder int32

const (
	SideOrder_BUY  SideOrder = 0
	SideOrder_SELL SideOrder = 1
)

// Enum value maps for SideOrder.
var (
	SideOrder_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	SideOrder_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x SideOrder) Enum() *SideOrder {
	p := new(SideOrder)
	*p = x
	return p
}

func (x SideOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SideOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_expose_orderbook_orderbook_proto_enumTypes[1].Descriptor()
}

func (SideOrder) Type() protoreflect.EnumType {
	return &file_expose_orderbook_orderbook_proto_enumTypes[1]
}

func (x SideOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SideOrder.Descriptor instead.
func (SideOrder) EnumDescriptor() ([]byte, []int) {
	return file_expose_orderbook_orderbook_proto_rawDescGZIP(), []int{1}
}

type OrderListResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Next   string   `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	Orders []*Order `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *OrderListResult) Reset() {
	*x = OrderListResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_orderbook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResult) ProtoMessage() {}

func (x *OrderListResult) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_orderbook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResult.ProtoReflect.Descriptor instead.
func (*OrderListResult) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *OrderListResult) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *OrderListResult) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status           string    `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UserId           string    `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Symbol           string    `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side             SideOrder `protobuf:"varint,5,opt,name=side,proto3,enum=orderbooks.SideOrder" json:"side,omitempty"`
	Type             TypeOrder `protobuf:"varint,6,opt,name=type,proto3,enum=orderbooks.TypeOrder" json:"type,omitempty"`
	CreatedAt        int64     `protobuf:"varint,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Price            string    `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`
	Paid             string    `protobuf:"bytes,9,opt,name=paid,proto3" json:"paid,omitempty"`
	AveragePrice     string    `protobuf:"bytes,10,opt,name=averagePrice,proto3" json:"averagePrice,omitempty"`
	Quantity         string    `protobuf:"bytes,11,opt,name=quantity,proto3" json:"quantity,omitempty"`
	FilledQuantity   string    `protobuf:"bytes,12,opt,name=filledQuantity,proto3" json:"filledQuantity,omitempty"`
	OriginalQuantity string    `protobuf:"bytes,13,opt,name=originalQuantity,proto3" json:"originalQuantity,omitempty"`
	PartiallyFilled  bool      `protobuf:"varint,14,opt,name=partiallyFilled,proto3" json:"partiallyFilled,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_orderbook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_orderbook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Order) GetSide() SideOrder {
	if x != nil {
		return x.Side
	}
	return SideOrder_BUY
}

func (x *Order) GetType() TypeOrder {
	if x != nil {
		return x.Type
	}
	return TypeOrder_LIMIT
}

func (x *Order) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetPaid() string {
	if x != nil {
		return x.Paid
	}
	return ""
}

func (x *Order) GetAveragePrice() string {
	if x != nil {
		return x.AveragePrice
	}
	return ""
}

func (x *Order) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Order) GetFilledQuantity() string {
	if x != nil {
		return x.FilledQuantity
	}
	return ""
}

func (x *Order) GetOriginalQuantity() string {
	if x != nil {
		return x.OriginalQuantity
	}
	return ""
}

func (x *Order) GetPartiallyFilled() bool {
	if x != nil {
		return x.PartiallyFilled
	}
	return false
}

type OrderListArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	From   string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Limit  int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	IsOpen bool   `protobuf:"varint,4,opt,name=isOpen,proto3" json:"isOpen,omitempty"`
}

func (x *OrderListArgs) Reset() {
	*x = OrderListArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_orderbook_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderListArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListArgs) ProtoMessage() {}

func (x *OrderListArgs) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_orderbook_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListArgs.ProtoReflect.Descriptor instead.
func (*OrderListArgs) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_orderbook_proto_rawDescGZIP(), []int{2}
}

func (x *OrderListArgs) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderListArgs) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *OrderListArgs) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *OrderListArgs) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

type SubscribeL2Args struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *SubscribeL2Args) Reset() {
	*x = SubscribeL2Args{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_orderbook_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeL2Args) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeL2Args) ProtoMessage() {}

func (x *SubscribeL2Args) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_orderbook_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeL2Args.ProtoReflect.Descriptor instead.
func (*SubscribeL2Args) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_orderbook_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeL2Args) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Prices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64         `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Asks      []*PriceLevel `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids      []*PriceLevel `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
}

func (x *Prices) Reset() {
	*x = Prices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_orderbook_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prices) ProtoMessage() {}

func (x *Prices) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_orderbook_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prices.ProtoReflect.Descriptor instead.
func (*Prices) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_orderbook_proto_rawDescGZIP(), []int{4}
}

func (x *Prices) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Prices) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *Prices) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

type PriceLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price    string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity string `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_orderbook_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_orderbook_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_orderbook_proto_rawDescGZIP(), []int{5}
}

func (x *PriceLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceLevel) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *PriceLevel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Limit: side Side, quantity decimal.Decimal, price decimal.Decimal
// Market: side Side, quantity decimal.Decimal
type OrderArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol   string    `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Type     TypeOrder `protobuf:"varint,2,opt,name=type,proto3,enum=orderbooks.TypeOrder" json:"type,omitempty"`
	Side     SideOrder `protobuf:"varint,3,opt,name=side,proto3,enum=orderbooks.SideOrder" json:"side,omitempty"`
	Quantity string    `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price    string    `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *OrderArgs) Reset() {
	*x = OrderArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_orderbook_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderArgs) ProtoMessage() {}

func (x *OrderArgs) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_orderbook_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderArgs.ProtoReflect.Descriptor instead.
func (*OrderArgs) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_orderbook_proto_rawDescGZIP(), []int{6}
}

func (x *OrderArgs) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderArgs) GetType() TypeOrder {
	if x != nil {
		return x.Type
	}
	return TypeOrder_LIMIT
}

func (x *OrderArgs) GetSide() SideOrder {
	if x != nil {
		return x.Side
	}
	return SideOrder_BUY
}

func (x *OrderArgs) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *OrderArgs) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

type CancelOrderArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
}

func (x *CancelOrderArgs) Reset() {
	*x = CancelOrderArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expose_orderbook_orderbook_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelOrderArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderArgs) ProtoMessage() {}

func (x *CancelOrderArgs) ProtoReflect() protoreflect.Message {
	mi := &file_expose_orderbook_orderbook_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderArgs.ProtoReflect.Descriptor instead.
func (*CancelOrderArgs) Descriptor() ([]byte, []int) {
	return file_expose_orderbook_orderbook_proto_rawDescGZIP(), []int{7}
}

func (x *CancelOrderArgs) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_expose_orderbook_orderbook_proto protoreflect.FileDescriptor

var file_expose_orderbook_orderbook_proto_rawDesc = []byte{
	0x0a, 0x20, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f,
	0x6f, 0x6b, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x22, 0x50,
	0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x65, 0x78, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f,
	0x6b, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x22, 0xbb, 0x03, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x12, 0x29, 0x0a, 0x04, 0x73, 0x69, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x53, 0x69,
	0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12, 0x29, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69, 0x64,
	0x12, 0x22, 0x0a, 0x0c, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x26, 0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64,
	0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x2a, 0x0a, 0x10, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x51, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x6c,
	0x79, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x70,
	0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x6c, 0x79, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x22, 0x69,
	0x0a, 0x0d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x69, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x22, 0x29, 0x0a, 0x0f, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4c, 0x32, 0x41, 0x72, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x7e, 0x0a, 0x06, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2a, 0x0a, 0x04,
	0x61, 0x73, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x52, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x2a, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f,
	0x6f, 0x6b, 0x73, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x04,
	0x62, 0x69, 0x64, 0x73, 0x22, 0x52, 0x0a, 0x0a, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x09, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x29,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x73, 0x69, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62,
	0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x04,
	0x73, 0x69, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x2a, 0x22, 0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x09, 0x0a, 0x05, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d,
	0x41, 0x52, 0x4b, 0x45, 0x54, 0x10, 0x01, 0x2a, 0x1e, 0x0a, 0x09, 0x53, 0x69, 0x64, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x55, 0x59, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x53, 0x45, 0x4c, 0x4c, 0x10, 0x01, 0x32, 0x94, 0x02, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x42, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x4c, 0x32, 0x12, 0x1b, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f,
	0x6b, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4c, 0x32, 0x41, 0x72,
	0x67, 0x73, 0x1a, 0x12, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3a, 0x0a, 0x0c, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x72, 0x67,
	0x73, 0x1a, 0x11, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0b, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f,
	0x6b, 0x73, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x72,
	0x67, 0x73, 0x1a, 0x11, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b,
	0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x67, 0x73, 0x1a,
	0x1b, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x50,
	0x0a, 0x1a, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x73, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x42, 0x0e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x20,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_expose_orderbook_orderbook_proto_rawDescOnce sync.Once
	file_expose_orderbook_orderbook_proto_rawDescData = file_expose_orderbook_orderbook_proto_rawDesc
)

func file_expose_orderbook_orderbook_proto_rawDescGZIP() []byte {
	file_expose_orderbook_orderbook_proto_rawDescOnce.Do(func() {
		file_expose_orderbook_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(file_expose_orderbook_orderbook_proto_rawDescData)
	})
	return file_expose_orderbook_orderbook_proto_rawDescData
}

var file_expose_orderbook_orderbook_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_expose_orderbook_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_expose_orderbook_orderbook_proto_goTypes = []interface{}{
	(TypeOrder)(0),          // 0: orderbooks.TypeOrder
	(SideOrder)(0),          // 1: orderbooks.SideOrder
	(*OrderListResult)(nil), // 2: orderbooks.OrderListResult
	(*Order)(nil),           // 3: orderbooks.Order
	(*OrderListArgs)(nil),   // 4: orderbooks.OrderListArgs
	(*SubscribeL2Args)(nil), // 5: orderbooks.SubscribeL2Args
	(*Prices)(nil),          // 6: orderbooks.Prices
	(*PriceLevel)(nil),      // 7: orderbooks.PriceLevel
	(*OrderArgs)(nil),       // 8: orderbooks.OrderArgs
	(*CancelOrderArgs)(nil), // 9: orderbooks.CancelOrderArgs
}
var file_expose_orderbook_orderbook_proto_depIdxs = []int32{
	3,  // 0: orderbooks.OrderListResult.orders:type_name -> orderbooks.Order
	1,  // 1: orderbooks.Order.side:type_name -> orderbooks.SideOrder
	0,  // 2: orderbooks.Order.type:type_name -> orderbooks.TypeOrder
	7,  // 3: orderbooks.Prices.asks:type_name -> orderbooks.PriceLevel
	7,  // 4: orderbooks.Prices.bids:type_name -> orderbooks.PriceLevel
	0,  // 5: orderbooks.OrderArgs.type:type_name -> orderbooks.TypeOrder
	1,  // 6: orderbooks.OrderArgs.side:type_name -> orderbooks.SideOrder
	5,  // 7: orderbooks.Orderbooks.SubscribeL2:input_type -> orderbooks.SubscribeL2Args
	8,  // 8: orderbooks.Orderbooks.ProcessOrder:input_type -> orderbooks.OrderArgs
	9,  // 9: orderbooks.Orderbooks.CancelOrder:input_type -> orderbooks.CancelOrderArgs
	4,  // 10: orderbooks.Orderbooks.OrderList:input_type -> orderbooks.OrderListArgs
	6,  // 11: orderbooks.Orderbooks.SubscribeL2:output_type -> orderbooks.Prices
	3,  // 12: orderbooks.Orderbooks.ProcessOrder:output_type -> orderbooks.Order
	3,  // 13: orderbooks.Orderbooks.CancelOrder:output_type -> orderbooks.Order
	2,  // 14: orderbooks.Orderbooks.OrderList:output_type -> orderbooks.OrderListResult
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_expose_orderbook_orderbook_proto_init() }
func file_expose_orderbook_orderbook_proto_init() {
	if File_expose_orderbook_orderbook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_expose_orderbook_orderbook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderListResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_orderbook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_orderbook_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderListArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_orderbook_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeL2Args); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_orderbook_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_orderbook_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PriceLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_orderbook_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expose_orderbook_orderbook_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelOrderArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_expose_orderbook_orderbook_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expose_orderbook_orderbook_proto_goTypes,
		DependencyIndexes: file_expose_orderbook_orderbook_proto_depIdxs,
		EnumInfos:         file_expose_orderbook_orderbook_proto_enumTypes,
		MessageInfos:      file_expose_orderbook_orderbook_proto_msgTypes,
	}.Build()
	File_expose_orderbook_orderbook_proto = out.File
	file_expose_orderbook_orderbook_proto_rawDesc = nil
	file_expose_orderbook_orderbook_proto_goTypes = nil
	file_expose_orderbook_orderbook_proto_depIdxs = nil
}
